services:
  - type: web
    name: medisync
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://trymaharshi_db_user:mongopass1@medisync.ly6ut3x.mongodb.net/?retryWrites=true&w=majority&appName=Medisync
      - key: JWT_SECRET
        value: a_very_secret_key_that_is_long_and_secure
      - key: FRONTEND_URL
        value: https://medisync-js.onrender.com